In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pyarrow
import pathlib
import gc
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, Bidirectional, \
                        Conv1D, Flatten,MaxPooling1D, ConvLSTM2D, \
                        TimeDistributed, RepeatVector
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint,ReduceLROnPlateau

ROOT = pathlib.Path().resolve()
DATA_FOLDER = ROOT / "data/bike"

print(DATA_FOLDER)

C:\Users\PatCa\Documents\PythonScripts\test_projects\big_data\bike_data\data\bike


In [3]:
def split_sequence(sequence, n_steps):
    X, y = [], []
    
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence) - 1:
            break
        
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
    
        

In [10]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_steps = 3
X,y = split_sequence(raw_seq, n_steps)

print(X,y)


[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]] [40 50 60 70 80 90]


In [ ]:
def print_curves(history, train_met, test_met):
    plt.figure()
    plt.plot(history.history[train_met], label='train')
    plt.plot(history.history[test_met], label='test')
    plt.legend()
    plt.show()
    
def print_curves(history, train_met, test_met):
    plt.figure()
    plt.plot(history.history[train_met], label='train')
    plt.plot(history.history[test_met], label='test')
    plt.legend()
    plt.show()

In [6]:
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps))
model.add(Dense(1,))

model.compile(optimizer=Adam(learning_rate=0.01), #'adam', 
              loss='mse', metrics='mae')

In [7]:
model.fit(X,y, epochs=2000, verbose=0)

In [8]:
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1,n_steps))
print(x_input)

[[70 80 90]]


In [9]:
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[101.58036]]


In [16]:
df = pd.read_csv('citi_test.csv')
df = df.drop(columns=['Unnamed: 0'])

In [19]:
display(df.head(5))
print(df.to_numpy().flatten())

,count_trips
0,133.0
1,272.0
2,283.0
3,187.0
4,120.0


[ 133.  272.  283.  187.  120.   72.  151.  198.  384.  555.  929. 1484.
 1963. 2433. 2526. 2384. 2102. 1558. 1216.  942.  843.  584.  415.  228.
  159.   99.   54.   43.   79.  389.]


In [26]:
raw_seq = df.to_numpy().flatten()
n_steps = 3
X,y = split_sequence(raw_seq, n_steps)

print(type(X), type(y))
print(X,y)


<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[ 133.  272.  283.]
 [ 272.  283.  187.]
 [ 283.  187.  120.]
 [ 187.  120.   72.]
 [ 120.   72.  151.]
 [  72.  151.  198.]
 [ 151.  198.  384.]
 [ 198.  384.  555.]
 [ 384.  555.  929.]
 [ 555.  929. 1484.]
 [ 929. 1484. 1963.]
 [1484. 1963. 2433.]
 [1963. 2433. 2526.]
 [2433. 2526. 2384.]
 [2526. 2384. 2102.]
 [2384. 2102. 1558.]
 [2102. 1558. 1216.]
 [1558. 1216.  942.]
 [1216.  942.  843.]
 [ 942.  843.  584.]
 [ 843.  584.  415.]
 [ 584.  415.  228.]
 [ 415.  228.  159.]
 [ 228.  159.   99.]
 [ 159.   99.   54.]
 [  99.   54.   43.]
 [  54.   43.   79.]] [ 187.  120.   72.  151.  198.  384.  555.  929. 1484. 1963. 2433. 2526.
 2384. 2102. 1558. 1216.  942.  843.  584.  415.  228.  159.   99.   54.
   43.   79.  389.]


In [22]:
model.fit(X,y, epochs=2000, verbose=0)

In [23]:
#     count_trips
# 30       1164.0
# 31       2280.0
# 32       3976.0
# 33       2471.0
# 34       1378.0

x_input = np.array([1164, 2280, 3976])
x_input = x_input.reshape((1,n_steps))
print(x_input)

[[1164 2280 3976]]


In [24]:
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[5865.8057]]
